<h1>Numpy: Notas de clase</h1>

In [2]:
import numpy as np

<h2>¿Qué es numpy?</h2>
<p>Numpy es una libreria de computación científica para python. El objeto central de numpy es el <b>ndarray</b> 
o N-dimensional array, que es una estructura de datos de alto rendimiento para cálculos numéricos.
    
Cuando el ndarray tiene una sola dimensión también recibe el nombre de <b>Vector</b>, cuando el ndarray tiene 2 
dimensiones, recibe el nombre de <b>Matriz</b> y por último si el ndarray tiene N-dimensiones simplemente recibe 
el nombre de <b>Array</b>.

Una de las características a mencionar es que los arrays son <b>homogéneos</b>, lo que significa que todos los datos dentro de un array son del mismo tipo, esto debido a que la homogeneidad de los datos proporciona una mayor eficiencia y un mejor rendimiento en el procesamiento de los datos. Si se quieren usar datos heterogéneos se recomienda usar estructuras de datos como un array tipo object o un dataframe de pandas.</p>

In [21]:
vector = np.array ([1, 2, 3, 4, 5])
vector

array([1, 2, 3, 4, 5])

In [22]:
matriz = np.array([[1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e']])
matriz

array([['1', '2', '3', '4', '5'],
       ['a', 'b', 'c', 'd', 'e']], dtype='<U21')

In [22]:
ndarray = np.array([[[1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e']],
                   [[6, 7, 8, 9, 10], ['f', 'g', 'h', 'i', 'j']],
                   [[11, 12, 13, 14, 15], ['k', 'l', 'm', 'n', 'ñ']]])
ndarray

array([[['1', '2', '3', '4', '5'],
        ['a', 'b', 'c', 'd', 'e']],

       [['6', '7', '8', '9', '10'],
        ['f', 'g', 'h', 'i', 'j']],

       [['11', '12', '13', '14', '15'],
        ['k', 'l', 'm', 'n', 'ñ']]], dtype='<U21')

<h2>Crear Arrays a partir de Tuplas o Listas</h2>

<p>Las tuplas y las listas son ambas estructuras de datos utilizadas en Python. Son colecciones <b>ordenadas</b> de datos, por un lado las tuplas se crean usando paréntesis (), o em método constructor tuple() y las listas usando llaves [] o el método constructor list(). La diferencia entre las tuplas y las listas radica en que las <b>tuplas son inmutables</b>, mientras que las <b>listas son mutables</b>, es decir que en estas últimas se pueden aplicar operaciones como añadir o eliminar elementos.</p>

In [24]:
tupla = ('Daniela', 'Camila', 'Samuel')
tupla

('Daniela', 'Camila', 'Samuel')

In [25]:
lista = ['Yesika', 'Javier', 'Leonardo']
lista

['Yesika', 'Javier', 'Leonardo']

<p>Usando numpy, podemos crear ndarrays a partir de tuplas y listas. Al crear un array a partir de una tupla o una lista, el array resutante será mutable y homogéneo, sin importar las carácteristicas previas de la estructura de datos original.</p>

In [26]:
arrayTupla = np.array(tupla)
arrayTupla

array(['Daniela', 'Camila', 'Samuel'], dtype='<U7')

In [27]:
arrayLista = np.array(lista)
arrayLista

array(['Yesika', 'Javier', 'Leonardo'], dtype='<U8')

<h2>Tipos de datos</h2>

<p>Podemos utilizar varios tipos de datos para crear un array. Algunos de los más comunes son los <b>enteros</b> como int8, int16, int32 e int64, los <b>decimales</b> o de punto flotante como float16, float32, float63, float128, los <b>complejos</b> como complex64 y complex128, los <b>booleanos</b> de tipo bool, los <b>strings</b> str y unicode, y los tipo <b>object</b>

Para conocer el tipo de datos de un arra podemos utiliar el atributo <b>dtype</b>. También podemos utilizar dtype como parámetro dentro de la creación del array para establecer el tipo de datos que vamos a utilizar. 
    
Para convertir el tipo de datos de un array podemos utilizar el método <b>astype</b>.
</p>

In [32]:
enteros = np.array([1,2, 3, 4, 5])
enteros.dtype

dtype('int64')

In [37]:
arrayTipificado = np.array([1, 2, 3, 4, 5], dtype = 'str')
arrayTipificado

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [43]:
arrayEntero = np.array([1, 2, 3, 4, 5])
arrayFloat = arrayEntero.astype('float64')
arrayEntero.dtype, arrayFloat.dtype

(dtype('int64'), dtype('float64'))

<h2>Manipulación de Arrays</h2>

<h3>Indexación</h3>

<p>Podemos acceder a los elementos de un array de numpy a través de sus índices, usamos la notación [] para especificar a que posición queremos acceder. Es importante tener en cuenta que la primera posición tiene índice 0.

En numpy usamos tres tipos de indexación. 
</p>

<h4>Indexación simple</h4>
<p>Accedemos a un solo elemento utilizando el índice</p>

In [7]:
indexSimple1 = np.array([1, 2, 3, 4, 5, 6])
indexSimple1[0]

1

In [5]:
indexSimple2 = np.array([['a', 'b'], ['c', 'd']])
indexSimple2[1]

array(['c', 'd'], dtype='<U1')

In [8]:
indexSimple3 = np.array([[['a', 'b'], ['c', 'd']],[[1, 2], [3, 4]],[['Hola', 'Como'], ['Estas', 'Hoy']]])
indexSimple3[2]

array([['Hola', 'Como'],
       ['Estas', 'Hoy']], dtype='<U21')

<h4>Indexación con múltiples dimensiones</h4>
<p>Accedemos a una elemento específico de un array de más de una dimensión.
El primer elemento del índice corresponde a la primera capa y asi sucesivamente</p>

In [14]:
indexMultiple1 = np.array([['Frutas', 'Verduras'],['Legumbres', 'Bebidas']])
indexMultiple1[0, 1]

'Verduras'

In [37]:
indexMultiple2 = np.array([[['a', 'b'], ['c', 'd']],[[1, 2], [3, 4]],[['Hola', 'Como'], ['Estas', 'Hoy']]])
indexMultiple2[1, 0, 0]


'1'

<h4>Indexación booleana</h4>
<p>Se seleccionan los elementos que cumplan con una condición dada.</p>

In [27]:
indexBooleano1 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 10])
condicion = indexBooleano1 < 72
indexBooleano1[condicion]

array([10, 20, 30, 40, 50, 60, 70, 10])

In [38]:
indexBooleano2 = np.array(['Uno', 'Dos', 'Tres'])
condicion2 = indexBooleano2 == 'Tres'
indexBooleano2[condicion2]

array(['Tres'], dtype='<U4')

<h3>Segmentación (slicing)</h3>

<p>A través del slicing podmeos extraer una porción o subconjunto de un array. Podemos seleccionar uno o varios elementos de manera precisa utilizando índices. La sintaxis básica para hacer slicing es:

array[inicio:fin:paso]

<b>Inicio</b> es el índice dónde empieza el slice, se incluye. <br> 
<b>Fin</b> es el índice dónde termina el slice, no se incluye. <br>
<b>Paso</b> es el tamaño del paso entre los elementos seleccionados. 
    
Si omitimos alguno de estos datos Numpy asumirá inicio = 0, fin como el tamaño total del array y paso = 1.
</p>  

<h4>Segmentación básica</h4>

In [5]:
slicingBasico = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])
slicingBasico[0:6]

array([1, 2, 3, 4, 5, 6])

<p>Podemos segmentar usando indices negativos</p>

In [41]:
slicingBasico[-5:-1]

array([6, 7, 8, 9])

<h4>Segmentación en arrays multidimensionales</h4>

<p>En arrays de <b>dos dimensiones</b> podemos hacer el slicing usando la siguiente sintaxis: <br>
array[filas, columnas]
</p>

In [20]:
slicing2d = np.array([['a', 'b', 'c'],['1', '2', '3'], ['P', 'Q', 'R']])
slicing2d[0:3, 0:2]

array([['a', 'b'],
       ['1', '2'],
       ['P', 'Q']], dtype='<U1')

<p>En arrays de <b>tres o mas dimensiones</b> podemos pensar en que estamos accediendo al array por capas. </p>

In [57]:
slicingMulti = np.array([[[1, 2],[3, 4]],[['a', 'b'],['c', 'd']]])
slicingMulti[0:2, 0:1, -1:2]

array([[['2']],

       [['b']]], dtype='<U21')

<h4>Segmentación por pasos</h4>


In [59]:
slicingSteps = np.array([10,11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
slicingSteps[::2]

array([10, 12, 14, 16, 18, 20])

In [62]:
slicingStepsMulti = np.array([['a', 'b', 'c'],['1', '2', '3'], ['P', 'Q', 'R']])
slicingStepsMulti[0:3:2, 0:3:2]

array([['a', 'c'],
       ['P', 'R']], dtype='<U1')